<div class="container">
  <div class="d-flex justify-content-center mt-3">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Create your account</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/create_account" method="post">
            
              <div class="form-group">
              <input type="text" value="<?php if(isset($this->view->user['fullName'])) { ?><?= $this->view->user['fullName']  ?><?php } ?>" name="fullName" class="form-control" placeholder="Full Name">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?php if(isset($this->view->user['email'])) { ?><?= $this->view->user['email']?><?php } ?>" name="email" class="form-control" placeholder="Email">
              </div>
              
              <div class="form-group">
                <input type="password" value="" name="password" class="form-control" placeholder="Password">
              </div>
              
              <div class="form-group">
                <input type="password" value="" name="confirmPassword" class="form-control" placeholder="Confirm password">
              </div>              
    
              <?php if($this->view->validateFullNameError)  {  ?>
                    
                  <small class="form-text text-danger">
                    <strong class="h6 text-center"><?=$this->view->validateFullNameErrorMessage?></strong>
                  </small>

              <?php } ?> 

              <?php if($this->view->validateEmailError)  {  ?>
                    
                  <small class="form-text text-danger">
                    <strong class="h6 text-center"><?=$this->view->validateEmailErrorMessage?></strong>
                  </small>
                   
              <?php } ?> 
        
              <?php if($this->view->validatePasswordError)  {  ?>
                    
                  <small class="form-text text-danger">
                    <strong class="h6 text-center"><?=$this->view->validatePasswordErrorMessage?></strong>
                  </small>
                   
              <?php } ?> 

              <?php if($this->view->validateConfirmPasswordError)  {  ?>
                    
                  <small class="form-text text-danger">
                    <strong class="h6 text-center"><?=$this->view->validateConfirmPasswordErrorMessage?></strong>
                  </small>
                 
              <?php } ?>  

              <?php if($this->view->emailAlreadyInUseError)  {  ?>
                  
                  <small class="form-text text-danger">
                     <strong class="h6 text-center"><?=$this->view->emailAlreadyInUseErrorMessage?></strong>
                  </small>
                   
              <?php } ?>  
              <button type="submit" class="btn btn-primary btn-block mt-3"><strong>Sign up</strong></button>
            
            </form> 
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  