<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Your account has been successfully created!</h2>
          </div>
          <br>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block"><strong>Click here to login</strong></a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  